const EVENTS = {
	connection: 'connection',
	CLIENT: {
		CREATE_ROOM: 'CREATE_ROOM',
		SEND_ROOM_MESSAGE: 'SEND_ROOM_MESSAGE',
		SEND_ROOM_DATA: 'SEND_ROOM_DATA',
		JOIN_ROOM: 'JOIN_ROOM',
		LEAVE_ROOM: 'LEAVE_ROOM'
	},
	SERVER: {
		ROOMS: 'ROOMS',
		JOINED_ROOM: 'JOINED_ROOM',
		LEFT_ROOM: 'LEFT_ROOM',
		ROOM_MESSAGE: 'ROOM_MESSAGE',
		ROOM_DATA: 'SEND_ROOM_DATA'
	}
};

export default EVENTS;
